/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import contentTypeBuilder from "@strapi/plugin-content-type-builder/strapi-admin";
import email from "@strapi/plugin-email/strapi-admin";
import upload from "@strapi/plugin-upload/strapi-admin";
import ckeditor from "@ckeditor/strapi-plugin-ckeditor/strapi-admin";
import colorPicker from "@strapi/plugin-color-picker/strapi-admin";
import documentation from "@strapi/plugin-documentation/strapi-admin";
import i18N from "@strapi/plugin-i18n/strapi-admin";
import sentry from "@strapi/plugin-sentry/strapi-admin";
import seo from "@strapi/plugin-seo/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import duplicateButton from "strapi-plugin-duplicate-button/strapi-admin";
import menus from "strapi-plugin-menus/strapi-admin";
import previewButton from "strapi-plugin-preview-button/strapi-admin";
import restCache from "strapi-plugin-rest-cache/strapi-admin";
import { renderAdmin } from "@strapi/admin/strapi-admin";

renderAdmin(document.getElementById("strapi"), {
  plugins: {
    "content-type-builder": contentTypeBuilder,
    email: email,
    upload: upload,
    ckeditor: ckeditor,
    "color-picker": colorPicker,
    documentation: documentation,
    i18n: i18N,
    sentry: sentry,
    seo: seo,
    "users-permissions": usersPermissions,
    "duplicate-button": duplicateButton,
    menus: menus,
    "preview-button": previewButton,
    "rest-cache": restCache,
  },
});
