
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'BlockPageAppLinksCard': typeof import("../components/BlockPageAppLinksCard.vue")['default']
    'BlockPageContentChapter': typeof import("../components/BlockPageContentChapter.vue")['default']
    'BlockPageContentIntro': typeof import("../components/BlockPageContentIntro.vue")['default']
    'BlockPageFaqItems': typeof import("../components/BlockPageFaqItems.vue")['default']
    'BlockPageHighlightedText': typeof import("../components/BlockPageHighlightedText.vue")['default']
    'BlockPageJobApplicationCard': typeof import("../components/BlockPageJobApplicationCard.vue")['default']
    'BlockPageJobOfferCards': typeof import("../components/BlockPageJobOfferCards.vue")['default']
    'BlockPageLivignoCardForm': typeof import("../components/BlockPageLivignoCardForm.vue")['default']
    'BlockPageLogos': typeof import("../components/BlockPageLogos.vue")['default']
    'BlockPageNewsletterCard': typeof import("../components/BlockPageNewsletterCard.vue")['default']
    'BlockPagePageLinkLine': typeof import("../components/BlockPagePageLinkLine.vue")['default']
    'BlockPageSliderCards': typeof import("../components/BlockPageSliderCards.vue")['default']
    'BlockPageSliderHero': typeof import("../components/BlockPageSliderHero.vue")['default']
    'BlockPageTestimonialCards': typeof import("../components/BlockPageTestimonialCards.vue")['default']
    'BlockPageTextCards': typeof import("../components/BlockPageTextCards.vue")['default']
    'BlockPageTextImages': typeof import("../components/BlockPageTextImages.vue")['default']
    'BlockPageTextMedia': typeof import("../components/BlockPageTextMedia.vue")['default']
    'BlockPromoPromoCards': typeof import("../components/BlockPromoPromoCards.vue")['default']
    'BlockTextItem': typeof import("../components/BlockTextItem.vue")['default']
    'DynamicBlock': typeof import("../components/DynamicBlock.vue")['default']
    'FaqGroup': typeof import("../components/FaqGroup.vue")['default']
    'FiltersCol': typeof import("../components/FiltersCol.vue")['default']
    'HeaderLangSwitcher': typeof import("../components/Header/LangSwitcher.vue")['default']
    'HeaderMenuDesktop': typeof import("../components/Header/MenuDesktop.vue")['default']
    'HeaderMenuMobile': typeof import("../components/Header/MenuMobile.vue")['default']
    'HeaderTheBreadcrumb': typeof import("../components/Header/TheBreadcrumb.vue")['default']
    'HeaderTheHeader': typeof import("../components/Header/TheHeader.vue")['default']
    'HeaderTopHeader': typeof import("../components/Header/TopHeader.vue")['default']
    'JobOffertCard': typeof import("../components/JobOffertCard.vue")['default']
    'PageHead': typeof import("../components/PageHead.vue")['default']
    'ProgressSpinner': typeof import("../components/ProgressSpinner.vue")['default']
    'PromoCards': typeof import("../components/PromoCards.vue")['default']
    'SvgIcon': typeof import("../components/SvgIcon.vue")['default']
    'TheFooter': typeof import("../components/TheFooter.vue")['default']
    'CommonsSortJobOfferts': typeof import("../components/commons/SortJobOfferts.vue")['default']
    'CommonsSwiperSlider': typeof import("../components/commons/SwiperSlider.vue")['default']
    'FormContactForm': typeof import("../components/form/ContactForm.vue")['default']
    'FormJobApplicationForm': typeof import("../components/form/JobApplicationForm.vue")['default']
    'FormNewsletterTopicForm': typeof import("../components/form/NewsletterTopicForm.vue")['default']
    'FormInputCheckbox': typeof import("../components/form/input/InputCheckbox.vue")['default']
    'FormInputFile': typeof import("../components/form/input/InputFile.vue")['default']
    'FormInputNumber': typeof import("../components/form/input/InputNumber.vue")['default']
    'FormInputRadio': typeof import("../components/form/input/InputRadio.vue")['default']
    'FormInputRange': typeof import("../components/form/input/InputRange.vue")['default']
    'FormInputSelect': typeof import("../components/form/input/InputSelect.vue")['default']
    'FormInputText': typeof import("../components/form/input/InputText.vue")['default']
    'FormInputTextarea': typeof import("../components/form/input/InputTextarea.vue")['default']
    'FormInputPromoFilterCheckbox': typeof import("../components/form/input/PromoFilterCheckbox.vue")['default']
    'ModalsBaseModal': typeof import("../components/modals/BaseModal.vue")['default']
    'ModalsJobFiltersModal': typeof import("../components/modals/JobFiltersModal.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
    'NuxtPicture': typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
    'NuxtLinkLocale': typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
    'SwitchLocalePathLink': typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
    'NuxtIcon': typeof import("../node_modules/nuxt-icons/dist/runtime/components/nuxt-icon.vue")['default']
    'PAutoComplete': typeof import("primevue/autocomplete")['default']
    'PCalendar': typeof import("primevue/calendar")['default']
    'PCascadeSelect': typeof import("primevue/cascadeselect")['default']
    'PCheckbox': typeof import("primevue/checkbox")['default']
    'PChips': typeof import("primevue/chips")['default']
    'PColorPicker': typeof import("primevue/colorpicker")['default']
    'PDropdown': typeof import("primevue/dropdown")['default']
    'PInputMask': typeof import("primevue/inputmask")['default']
    'PInputNumber': typeof import("primevue/inputnumber")['default']
    'PInputSwitch': typeof import("primevue/inputswitch")['default']
    'PInputText': typeof import("primevue/inputtext")['default']
    'PKnob': typeof import("primevue/knob")['default']
    'PListbox': typeof import("primevue/listbox")['default']
    'PMultiSelect': typeof import("primevue/multiselect")['default']
    'PPassword': typeof import("primevue/password")['default']
    'PRadioButton': typeof import("primevue/radiobutton")['default']
    'PRating': typeof import("primevue/rating")['default']
    'PSelectButton': typeof import("primevue/selectbutton")['default']
    'PSlider': typeof import("primevue/slider")['default']
    'PTextarea': typeof import("primevue/textarea")['default']
    'PToggleButton': typeof import("primevue/togglebutton")['default']
    'PTreeSelect': typeof import("primevue/treeselect")['default']
    'PTriStateCheckbox': typeof import("primevue/tristatecheckbox")['default']
    'PButton': typeof import("primevue/button")['default']
    'PSpeedDial': typeof import("primevue/speeddial")['default']
    'PSplitButton': typeof import("primevue/splitbutton")['default']
    'PColumn': typeof import("primevue/column")['default']
    'PRow': typeof import("primevue/row")['default']
    'PColumnGroup': typeof import("primevue/columngroup")['default']
    'PDataTable': typeof import("primevue/datatable")['default']
    'PDataView': typeof import("primevue/dataview")['default']
    'PDataViewLayoutOptions': typeof import("primevue/dataviewlayoutoptions")['default']
    'POrderList': typeof import("primevue/orderlist")['default']
    'POrganizationChart': typeof import("primevue/organizationchart")['default']
    'PPaginator': typeof import("primevue/paginator")['default']
    'PPickList': typeof import("primevue/picklist")['default']
    'PTree': typeof import("primevue/tree")['default']
    'PTreeTable': typeof import("primevue/treetable")['default']
    'PTimeline': typeof import("primevue/timeline")['default']
    'PVirtualScroller': typeof import("primevue/virtualscroller")['default']
    'PAccordion': typeof import("primevue/accordion")['default']
    'PAccordionTab': typeof import("primevue/accordiontab")['default']
    'PCard': typeof import("primevue/card")['default']
    'PDeferredContent': typeof import("primevue/deferredcontent")['default']
    'PDivider': typeof import("primevue/divider")['default']
    'PFieldset': typeof import("primevue/fieldset")['default']
    'PPanel': typeof import("primevue/panel")['default']
    'PScrollPanel': typeof import("primevue/scrollpanel")['default']
    'PSplitter': typeof import("primevue/splitter")['default']
    'PSplitterPanel': typeof import("primevue/splitterpanel")['default']
    'PTabView': typeof import("primevue/tabview")['default']
    'PTabPanel': typeof import("primevue/tabpanel")['default']
    'PToolbar': typeof import("primevue/toolbar")['default']
    'PConfirmDialog': typeof import("primevue/confirmdialog")['default']
    'PConfirmPopup': typeof import("primevue/confirmpopup")['default']
    'PDialog': typeof import("primevue/dialog")['default']
    'PDynamicDialog': typeof import("primevue/dynamicdialog")['default']
    'POverlayPanel': typeof import("primevue/overlaypanel")['default']
    'PSidebar': typeof import("primevue/sidebar")['default']
    'PFileUpload': typeof import("primevue/fileupload")['default']
    'PBreadcrumb': typeof import("primevue/breadcrumb")['default']
    'PContextMenu': typeof import("primevue/contextmenu")['default']
    'PDock': typeof import("primevue/dock")['default']
    'PMenu': typeof import("primevue/menu")['default']
    'PMenubar': typeof import("primevue/menubar")['default']
    'PMegaMenu': typeof import("primevue/megamenu")['default']
    'PPanelMenu': typeof import("primevue/panelmenu")['default']
    'PSteps': typeof import("primevue/steps")['default']
    'PTabMenu': typeof import("primevue/tabmenu")['default']
    'PTieredMenu': typeof import("primevue/tieredmenu")['default']
    'PMessage': typeof import("primevue/message")['default']
    'PInlineMessage': typeof import("primevue/inlinemessage")['default']
    'PToast': typeof import("primevue/toast")['default']
    'PCarousel': typeof import("primevue/carousel")['default']
    'PGalleria': typeof import("primevue/galleria")['default']
    'PImage': typeof import("primevue/image")['default']
    'PAvatar': typeof import("primevue/avatar")['default']
    'PAvatarGroup': typeof import("primevue/avatargroup")['default']
    'PBadge': typeof import("primevue/badge")['default']
    'PBlockUI': typeof import("primevue/blockui")['default']
    'PChip': typeof import("primevue/chip")['default']
    'PInplace': typeof import("primevue/inplace")['default']
    'PScrollTop': typeof import("primevue/scrolltop")['default']
    'PSkeleton': typeof import("primevue/skeleton")['default']
    'PProgressBar': typeof import("primevue/progressbar")['default']
    'PProgressSpinner': typeof import("primevue/progressspinner")['default']
    'PTag': typeof import("primevue/tag")['default']
    'PTerminal': typeof import("primevue/terminal")['default']
    'ErrorMessage': typeof import("vee-validate")['ErrorMessage']
    'Field': typeof import("vee-validate")['Field']
    'FieldArray': typeof import("vee-validate")['FieldArray']
    'Form': typeof import("vee-validate")['Form']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyBlockPageAppLinksCard': typeof import("../components/BlockPageAppLinksCard.vue")['default']
    'LazyBlockPageContentChapter': typeof import("../components/BlockPageContentChapter.vue")['default']
    'LazyBlockPageContentIntro': typeof import("../components/BlockPageContentIntro.vue")['default']
    'LazyBlockPageFaqItems': typeof import("../components/BlockPageFaqItems.vue")['default']
    'LazyBlockPageHighlightedText': typeof import("../components/BlockPageHighlightedText.vue")['default']
    'LazyBlockPageJobApplicationCard': typeof import("../components/BlockPageJobApplicationCard.vue")['default']
    'LazyBlockPageJobOfferCards': typeof import("../components/BlockPageJobOfferCards.vue")['default']
    'LazyBlockPageLivignoCardForm': typeof import("../components/BlockPageLivignoCardForm.vue")['default']
    'LazyBlockPageLogos': typeof import("../components/BlockPageLogos.vue")['default']
    'LazyBlockPageNewsletterCard': typeof import("../components/BlockPageNewsletterCard.vue")['default']
    'LazyBlockPagePageLinkLine': typeof import("../components/BlockPagePageLinkLine.vue")['default']
    'LazyBlockPageSliderCards': typeof import("../components/BlockPageSliderCards.vue")['default']
    'LazyBlockPageSliderHero': typeof import("../components/BlockPageSliderHero.vue")['default']
    'LazyBlockPageTestimonialCards': typeof import("../components/BlockPageTestimonialCards.vue")['default']
    'LazyBlockPageTextCards': typeof import("../components/BlockPageTextCards.vue")['default']
    'LazyBlockPageTextImages': typeof import("../components/BlockPageTextImages.vue")['default']
    'LazyBlockPageTextMedia': typeof import("../components/BlockPageTextMedia.vue")['default']
    'LazyBlockPromoPromoCards': typeof import("../components/BlockPromoPromoCards.vue")['default']
    'LazyBlockTextItem': typeof import("../components/BlockTextItem.vue")['default']
    'LazyDynamicBlock': typeof import("../components/DynamicBlock.vue")['default']
    'LazyFaqGroup': typeof import("../components/FaqGroup.vue")['default']
    'LazyFiltersCol': typeof import("../components/FiltersCol.vue")['default']
    'LazyHeaderLangSwitcher': typeof import("../components/Header/LangSwitcher.vue")['default']
    'LazyHeaderMenuDesktop': typeof import("../components/Header/MenuDesktop.vue")['default']
    'LazyHeaderMenuMobile': typeof import("../components/Header/MenuMobile.vue")['default']
    'LazyHeaderTheBreadcrumb': typeof import("../components/Header/TheBreadcrumb.vue")['default']
    'LazyHeaderTheHeader': typeof import("../components/Header/TheHeader.vue")['default']
    'LazyHeaderTopHeader': typeof import("../components/Header/TopHeader.vue")['default']
    'LazyJobOffertCard': typeof import("../components/JobOffertCard.vue")['default']
    'LazyPageHead': typeof import("../components/PageHead.vue")['default']
    'LazyProgressSpinner': typeof import("../components/ProgressSpinner.vue")['default']
    'LazyPromoCards': typeof import("../components/PromoCards.vue")['default']
    'LazySvgIcon': typeof import("../components/SvgIcon.vue")['default']
    'LazyTheFooter': typeof import("../components/TheFooter.vue")['default']
    'LazyCommonsSortJobOfferts': typeof import("../components/commons/SortJobOfferts.vue")['default']
    'LazyCommonsSwiperSlider': typeof import("../components/commons/SwiperSlider.vue")['default']
    'LazyFormContactForm': typeof import("../components/form/ContactForm.vue")['default']
    'LazyFormJobApplicationForm': typeof import("../components/form/JobApplicationForm.vue")['default']
    'LazyFormNewsletterTopicForm': typeof import("../components/form/NewsletterTopicForm.vue")['default']
    'LazyFormInputCheckbox': typeof import("../components/form/input/InputCheckbox.vue")['default']
    'LazyFormInputFile': typeof import("../components/form/input/InputFile.vue")['default']
    'LazyFormInputNumber': typeof import("../components/form/input/InputNumber.vue")['default']
    'LazyFormInputRadio': typeof import("../components/form/input/InputRadio.vue")['default']
    'LazyFormInputRange': typeof import("../components/form/input/InputRange.vue")['default']
    'LazyFormInputSelect': typeof import("../components/form/input/InputSelect.vue")['default']
    'LazyFormInputText': typeof import("../components/form/input/InputText.vue")['default']
    'LazyFormInputTextarea': typeof import("../components/form/input/InputTextarea.vue")['default']
    'LazyFormInputPromoFilterCheckbox': typeof import("../components/form/input/PromoFilterCheckbox.vue")['default']
    'LazyModalsBaseModal': typeof import("../components/modals/BaseModal.vue")['default']
    'LazyModalsJobFiltersModal': typeof import("../components/modals/JobFiltersModal.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
    'LazyNuxtPicture': typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
    'LazyNuxtLinkLocale': typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
    'LazySwitchLocalePathLink': typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
    'LazyNuxtIcon': typeof import("../node_modules/nuxt-icons/dist/runtime/components/nuxt-icon.vue")['default']
    'LazyPAutoComplete': typeof import("primevue/autocomplete")['default']
    'LazyPCalendar': typeof import("primevue/calendar")['default']
    'LazyPCascadeSelect': typeof import("primevue/cascadeselect")['default']
    'LazyPCheckbox': typeof import("primevue/checkbox")['default']
    'LazyPChips': typeof import("primevue/chips")['default']
    'LazyPColorPicker': typeof import("primevue/colorpicker")['default']
    'LazyPDropdown': typeof import("primevue/dropdown")['default']
    'LazyPInputMask': typeof import("primevue/inputmask")['default']
    'LazyPInputNumber': typeof import("primevue/inputnumber")['default']
    'LazyPInputSwitch': typeof import("primevue/inputswitch")['default']
    'LazyPInputText': typeof import("primevue/inputtext")['default']
    'LazyPKnob': typeof import("primevue/knob")['default']
    'LazyPListbox': typeof import("primevue/listbox")['default']
    'LazyPMultiSelect': typeof import("primevue/multiselect")['default']
    'LazyPPassword': typeof import("primevue/password")['default']
    'LazyPRadioButton': typeof import("primevue/radiobutton")['default']
    'LazyPRating': typeof import("primevue/rating")['default']
    'LazyPSelectButton': typeof import("primevue/selectbutton")['default']
    'LazyPSlider': typeof import("primevue/slider")['default']
    'LazyPTextarea': typeof import("primevue/textarea")['default']
    'LazyPToggleButton': typeof import("primevue/togglebutton")['default']
    'LazyPTreeSelect': typeof import("primevue/treeselect")['default']
    'LazyPTriStateCheckbox': typeof import("primevue/tristatecheckbox")['default']
    'LazyPButton': typeof import("primevue/button")['default']
    'LazyPSpeedDial': typeof import("primevue/speeddial")['default']
    'LazyPSplitButton': typeof import("primevue/splitbutton")['default']
    'LazyPColumn': typeof import("primevue/column")['default']
    'LazyPRow': typeof import("primevue/row")['default']
    'LazyPColumnGroup': typeof import("primevue/columngroup")['default']
    'LazyPDataTable': typeof import("primevue/datatable")['default']
    'LazyPDataView': typeof import("primevue/dataview")['default']
    'LazyPDataViewLayoutOptions': typeof import("primevue/dataviewlayoutoptions")['default']
    'LazyPOrderList': typeof import("primevue/orderlist")['default']
    'LazyPOrganizationChart': typeof import("primevue/organizationchart")['default']
    'LazyPPaginator': typeof import("primevue/paginator")['default']
    'LazyPPickList': typeof import("primevue/picklist")['default']
    'LazyPTree': typeof import("primevue/tree")['default']
    'LazyPTreeTable': typeof import("primevue/treetable")['default']
    'LazyPTimeline': typeof import("primevue/timeline")['default']
    'LazyPVirtualScroller': typeof import("primevue/virtualscroller")['default']
    'LazyPAccordion': typeof import("primevue/accordion")['default']
    'LazyPAccordionTab': typeof import("primevue/accordiontab")['default']
    'LazyPCard': typeof import("primevue/card")['default']
    'LazyPDeferredContent': typeof import("primevue/deferredcontent")['default']
    'LazyPDivider': typeof import("primevue/divider")['default']
    'LazyPFieldset': typeof import("primevue/fieldset")['default']
    'LazyPPanel': typeof import("primevue/panel")['default']
    'LazyPScrollPanel': typeof import("primevue/scrollpanel")['default']
    'LazyPSplitter': typeof import("primevue/splitter")['default']
    'LazyPSplitterPanel': typeof import("primevue/splitterpanel")['default']
    'LazyPTabView': typeof import("primevue/tabview")['default']
    'LazyPTabPanel': typeof import("primevue/tabpanel")['default']
    'LazyPToolbar': typeof import("primevue/toolbar")['default']
    'LazyPConfirmDialog': typeof import("primevue/confirmdialog")['default']
    'LazyPConfirmPopup': typeof import("primevue/confirmpopup")['default']
    'LazyPDialog': typeof import("primevue/dialog")['default']
    'LazyPDynamicDialog': typeof import("primevue/dynamicdialog")['default']
    'LazyPOverlayPanel': typeof import("primevue/overlaypanel")['default']
    'LazyPSidebar': typeof import("primevue/sidebar")['default']
    'LazyPFileUpload': typeof import("primevue/fileupload")['default']
    'LazyPBreadcrumb': typeof import("primevue/breadcrumb")['default']
    'LazyPContextMenu': typeof import("primevue/contextmenu")['default']
    'LazyPDock': typeof import("primevue/dock")['default']
    'LazyPMenu': typeof import("primevue/menu")['default']
    'LazyPMenubar': typeof import("primevue/menubar")['default']
    'LazyPMegaMenu': typeof import("primevue/megamenu")['default']
    'LazyPPanelMenu': typeof import("primevue/panelmenu")['default']
    'LazyPSteps': typeof import("primevue/steps")['default']
    'LazyPTabMenu': typeof import("primevue/tabmenu")['default']
    'LazyPTieredMenu': typeof import("primevue/tieredmenu")['default']
    'LazyPMessage': typeof import("primevue/message")['default']
    'LazyPInlineMessage': typeof import("primevue/inlinemessage")['default']
    'LazyPToast': typeof import("primevue/toast")['default']
    'LazyPCarousel': typeof import("primevue/carousel")['default']
    'LazyPGalleria': typeof import("primevue/galleria")['default']
    'LazyPImage': typeof import("primevue/image")['default']
    'LazyPAvatar': typeof import("primevue/avatar")['default']
    'LazyPAvatarGroup': typeof import("primevue/avatargroup")['default']
    'LazyPBadge': typeof import("primevue/badge")['default']
    'LazyPBlockUI': typeof import("primevue/blockui")['default']
    'LazyPChip': typeof import("primevue/chip")['default']
    'LazyPInplace': typeof import("primevue/inplace")['default']
    'LazyPScrollTop': typeof import("primevue/scrolltop")['default']
    'LazyPSkeleton': typeof import("primevue/skeleton")['default']
    'LazyPProgressBar': typeof import("primevue/progressbar")['default']
    'LazyPProgressSpinner': typeof import("primevue/progressspinner")['default']
    'LazyPTag': typeof import("primevue/tag")['default']
    'LazyPTerminal': typeof import("primevue/terminal")['default']
    'LazyErrorMessage': typeof import("vee-validate")['ErrorMessage']
    'LazyField': typeof import("vee-validate")['Field']
    'LazyFieldArray': typeof import("vee-validate")['FieldArray']
    'LazyForm': typeof import("vee-validate")['Form']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const BlockPageAppLinksCard: typeof import("../components/BlockPageAppLinksCard.vue")['default']
export const BlockPageContentChapter: typeof import("../components/BlockPageContentChapter.vue")['default']
export const BlockPageContentIntro: typeof import("../components/BlockPageContentIntro.vue")['default']
export const BlockPageFaqItems: typeof import("../components/BlockPageFaqItems.vue")['default']
export const BlockPageHighlightedText: typeof import("../components/BlockPageHighlightedText.vue")['default']
export const BlockPageJobApplicationCard: typeof import("../components/BlockPageJobApplicationCard.vue")['default']
export const BlockPageJobOfferCards: typeof import("../components/BlockPageJobOfferCards.vue")['default']
export const BlockPageLivignoCardForm: typeof import("../components/BlockPageLivignoCardForm.vue")['default']
export const BlockPageLogos: typeof import("../components/BlockPageLogos.vue")['default']
export const BlockPageNewsletterCard: typeof import("../components/BlockPageNewsletterCard.vue")['default']
export const BlockPagePageLinkLine: typeof import("../components/BlockPagePageLinkLine.vue")['default']
export const BlockPageSliderCards: typeof import("../components/BlockPageSliderCards.vue")['default']
export const BlockPageSliderHero: typeof import("../components/BlockPageSliderHero.vue")['default']
export const BlockPageTestimonialCards: typeof import("../components/BlockPageTestimonialCards.vue")['default']
export const BlockPageTextCards: typeof import("../components/BlockPageTextCards.vue")['default']
export const BlockPageTextImages: typeof import("../components/BlockPageTextImages.vue")['default']
export const BlockPageTextMedia: typeof import("../components/BlockPageTextMedia.vue")['default']
export const BlockPromoPromoCards: typeof import("../components/BlockPromoPromoCards.vue")['default']
export const BlockTextItem: typeof import("../components/BlockTextItem.vue")['default']
export const DynamicBlock: typeof import("../components/DynamicBlock.vue")['default']
export const FaqGroup: typeof import("../components/FaqGroup.vue")['default']
export const FiltersCol: typeof import("../components/FiltersCol.vue")['default']
export const HeaderLangSwitcher: typeof import("../components/Header/LangSwitcher.vue")['default']
export const HeaderMenuDesktop: typeof import("../components/Header/MenuDesktop.vue")['default']
export const HeaderMenuMobile: typeof import("../components/Header/MenuMobile.vue")['default']
export const HeaderTheBreadcrumb: typeof import("../components/Header/TheBreadcrumb.vue")['default']
export const HeaderTheHeader: typeof import("../components/Header/TheHeader.vue")['default']
export const HeaderTopHeader: typeof import("../components/Header/TopHeader.vue")['default']
export const JobOffertCard: typeof import("../components/JobOffertCard.vue")['default']
export const PageHead: typeof import("../components/PageHead.vue")['default']
export const ProgressSpinner: typeof import("../components/ProgressSpinner.vue")['default']
export const PromoCards: typeof import("../components/PromoCards.vue")['default']
export const SvgIcon: typeof import("../components/SvgIcon.vue")['default']
export const TheFooter: typeof import("../components/TheFooter.vue")['default']
export const CommonsSortJobOfferts: typeof import("../components/commons/SortJobOfferts.vue")['default']
export const CommonsSwiperSlider: typeof import("../components/commons/SwiperSlider.vue")['default']
export const FormContactForm: typeof import("../components/form/ContactForm.vue")['default']
export const FormJobApplicationForm: typeof import("../components/form/JobApplicationForm.vue")['default']
export const FormNewsletterTopicForm: typeof import("../components/form/NewsletterTopicForm.vue")['default']
export const FormInputCheckbox: typeof import("../components/form/input/InputCheckbox.vue")['default']
export const FormInputFile: typeof import("../components/form/input/InputFile.vue")['default']
export const FormInputNumber: typeof import("../components/form/input/InputNumber.vue")['default']
export const FormInputRadio: typeof import("../components/form/input/InputRadio.vue")['default']
export const FormInputRange: typeof import("../components/form/input/InputRange.vue")['default']
export const FormInputSelect: typeof import("../components/form/input/InputSelect.vue")['default']
export const FormInputText: typeof import("../components/form/input/InputText.vue")['default']
export const FormInputTextarea: typeof import("../components/form/input/InputTextarea.vue")['default']
export const FormInputPromoFilterCheckbox: typeof import("../components/form/input/PromoFilterCheckbox.vue")['default']
export const ModalsBaseModal: typeof import("../components/modals/BaseModal.vue")['default']
export const ModalsJobFiltersModal: typeof import("../components/modals/JobFiltersModal.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
export const NuxtPicture: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
export const NuxtLinkLocale: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
export const SwitchLocalePathLink: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
export const NuxtIcon: typeof import("../node_modules/nuxt-icons/dist/runtime/components/nuxt-icon.vue")['default']
export const PAutoComplete: typeof import("primevue/autocomplete")['default']
export const PCalendar: typeof import("primevue/calendar")['default']
export const PCascadeSelect: typeof import("primevue/cascadeselect")['default']
export const PCheckbox: typeof import("primevue/checkbox")['default']
export const PChips: typeof import("primevue/chips")['default']
export const PColorPicker: typeof import("primevue/colorpicker")['default']
export const PDropdown: typeof import("primevue/dropdown")['default']
export const PInputMask: typeof import("primevue/inputmask")['default']
export const PInputNumber: typeof import("primevue/inputnumber")['default']
export const PInputSwitch: typeof import("primevue/inputswitch")['default']
export const PInputText: typeof import("primevue/inputtext")['default']
export const PKnob: typeof import("primevue/knob")['default']
export const PListbox: typeof import("primevue/listbox")['default']
export const PMultiSelect: typeof import("primevue/multiselect")['default']
export const PPassword: typeof import("primevue/password")['default']
export const PRadioButton: typeof import("primevue/radiobutton")['default']
export const PRating: typeof import("primevue/rating")['default']
export const PSelectButton: typeof import("primevue/selectbutton")['default']
export const PSlider: typeof import("primevue/slider")['default']
export const PTextarea: typeof import("primevue/textarea")['default']
export const PToggleButton: typeof import("primevue/togglebutton")['default']
export const PTreeSelect: typeof import("primevue/treeselect")['default']
export const PTriStateCheckbox: typeof import("primevue/tristatecheckbox")['default']
export const PButton: typeof import("primevue/button")['default']
export const PSpeedDial: typeof import("primevue/speeddial")['default']
export const PSplitButton: typeof import("primevue/splitbutton")['default']
export const PColumn: typeof import("primevue/column")['default']
export const PRow: typeof import("primevue/row")['default']
export const PColumnGroup: typeof import("primevue/columngroup")['default']
export const PDataTable: typeof import("primevue/datatable")['default']
export const PDataView: typeof import("primevue/dataview")['default']
export const PDataViewLayoutOptions: typeof import("primevue/dataviewlayoutoptions")['default']
export const POrderList: typeof import("primevue/orderlist")['default']
export const POrganizationChart: typeof import("primevue/organizationchart")['default']
export const PPaginator: typeof import("primevue/paginator")['default']
export const PPickList: typeof import("primevue/picklist")['default']
export const PTree: typeof import("primevue/tree")['default']
export const PTreeTable: typeof import("primevue/treetable")['default']
export const PTimeline: typeof import("primevue/timeline")['default']
export const PVirtualScroller: typeof import("primevue/virtualscroller")['default']
export const PAccordion: typeof import("primevue/accordion")['default']
export const PAccordionTab: typeof import("primevue/accordiontab")['default']
export const PCard: typeof import("primevue/card")['default']
export const PDeferredContent: typeof import("primevue/deferredcontent")['default']
export const PDivider: typeof import("primevue/divider")['default']
export const PFieldset: typeof import("primevue/fieldset")['default']
export const PPanel: typeof import("primevue/panel")['default']
export const PScrollPanel: typeof import("primevue/scrollpanel")['default']
export const PSplitter: typeof import("primevue/splitter")['default']
export const PSplitterPanel: typeof import("primevue/splitterpanel")['default']
export const PTabView: typeof import("primevue/tabview")['default']
export const PTabPanel: typeof import("primevue/tabpanel")['default']
export const PToolbar: typeof import("primevue/toolbar")['default']
export const PConfirmDialog: typeof import("primevue/confirmdialog")['default']
export const PConfirmPopup: typeof import("primevue/confirmpopup")['default']
export const PDialog: typeof import("primevue/dialog")['default']
export const PDynamicDialog: typeof import("primevue/dynamicdialog")['default']
export const POverlayPanel: typeof import("primevue/overlaypanel")['default']
export const PSidebar: typeof import("primevue/sidebar")['default']
export const PFileUpload: typeof import("primevue/fileupload")['default']
export const PBreadcrumb: typeof import("primevue/breadcrumb")['default']
export const PContextMenu: typeof import("primevue/contextmenu")['default']
export const PDock: typeof import("primevue/dock")['default']
export const PMenu: typeof import("primevue/menu")['default']
export const PMenubar: typeof import("primevue/menubar")['default']
export const PMegaMenu: typeof import("primevue/megamenu")['default']
export const PPanelMenu: typeof import("primevue/panelmenu")['default']
export const PSteps: typeof import("primevue/steps")['default']
export const PTabMenu: typeof import("primevue/tabmenu")['default']
export const PTieredMenu: typeof import("primevue/tieredmenu")['default']
export const PMessage: typeof import("primevue/message")['default']
export const PInlineMessage: typeof import("primevue/inlinemessage")['default']
export const PToast: typeof import("primevue/toast")['default']
export const PCarousel: typeof import("primevue/carousel")['default']
export const PGalleria: typeof import("primevue/galleria")['default']
export const PImage: typeof import("primevue/image")['default']
export const PAvatar: typeof import("primevue/avatar")['default']
export const PAvatarGroup: typeof import("primevue/avatargroup")['default']
export const PBadge: typeof import("primevue/badge")['default']
export const PBlockUI: typeof import("primevue/blockui")['default']
export const PChip: typeof import("primevue/chip")['default']
export const PInplace: typeof import("primevue/inplace")['default']
export const PScrollTop: typeof import("primevue/scrolltop")['default']
export const PSkeleton: typeof import("primevue/skeleton")['default']
export const PProgressBar: typeof import("primevue/progressbar")['default']
export const PProgressSpinner: typeof import("primevue/progressspinner")['default']
export const PTag: typeof import("primevue/tag")['default']
export const PTerminal: typeof import("primevue/terminal")['default']
export const ErrorMessage: typeof import("vee-validate")['ErrorMessage']
export const Field: typeof import("vee-validate")['Field']
export const FieldArray: typeof import("vee-validate")['FieldArray']
export const Form: typeof import("vee-validate")['Form']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyBlockPageAppLinksCard: typeof import("../components/BlockPageAppLinksCard.vue")['default']
export const LazyBlockPageContentChapter: typeof import("../components/BlockPageContentChapter.vue")['default']
export const LazyBlockPageContentIntro: typeof import("../components/BlockPageContentIntro.vue")['default']
export const LazyBlockPageFaqItems: typeof import("../components/BlockPageFaqItems.vue")['default']
export const LazyBlockPageHighlightedText: typeof import("../components/BlockPageHighlightedText.vue")['default']
export const LazyBlockPageJobApplicationCard: typeof import("../components/BlockPageJobApplicationCard.vue")['default']
export const LazyBlockPageJobOfferCards: typeof import("../components/BlockPageJobOfferCards.vue")['default']
export const LazyBlockPageLivignoCardForm: typeof import("../components/BlockPageLivignoCardForm.vue")['default']
export const LazyBlockPageLogos: typeof import("../components/BlockPageLogos.vue")['default']
export const LazyBlockPageNewsletterCard: typeof import("../components/BlockPageNewsletterCard.vue")['default']
export const LazyBlockPagePageLinkLine: typeof import("../components/BlockPagePageLinkLine.vue")['default']
export const LazyBlockPageSliderCards: typeof import("../components/BlockPageSliderCards.vue")['default']
export const LazyBlockPageSliderHero: typeof import("../components/BlockPageSliderHero.vue")['default']
export const LazyBlockPageTestimonialCards: typeof import("../components/BlockPageTestimonialCards.vue")['default']
export const LazyBlockPageTextCards: typeof import("../components/BlockPageTextCards.vue")['default']
export const LazyBlockPageTextImages: typeof import("../components/BlockPageTextImages.vue")['default']
export const LazyBlockPageTextMedia: typeof import("../components/BlockPageTextMedia.vue")['default']
export const LazyBlockPromoPromoCards: typeof import("../components/BlockPromoPromoCards.vue")['default']
export const LazyBlockTextItem: typeof import("../components/BlockTextItem.vue")['default']
export const LazyDynamicBlock: typeof import("../components/DynamicBlock.vue")['default']
export const LazyFaqGroup: typeof import("../components/FaqGroup.vue")['default']
export const LazyFiltersCol: typeof import("../components/FiltersCol.vue")['default']
export const LazyHeaderLangSwitcher: typeof import("../components/Header/LangSwitcher.vue")['default']
export const LazyHeaderMenuDesktop: typeof import("../components/Header/MenuDesktop.vue")['default']
export const LazyHeaderMenuMobile: typeof import("../components/Header/MenuMobile.vue")['default']
export const LazyHeaderTheBreadcrumb: typeof import("../components/Header/TheBreadcrumb.vue")['default']
export const LazyHeaderTheHeader: typeof import("../components/Header/TheHeader.vue")['default']
export const LazyHeaderTopHeader: typeof import("../components/Header/TopHeader.vue")['default']
export const LazyJobOffertCard: typeof import("../components/JobOffertCard.vue")['default']
export const LazyPageHead: typeof import("../components/PageHead.vue")['default']
export const LazyProgressSpinner: typeof import("../components/ProgressSpinner.vue")['default']
export const LazyPromoCards: typeof import("../components/PromoCards.vue")['default']
export const LazySvgIcon: typeof import("../components/SvgIcon.vue")['default']
export const LazyTheFooter: typeof import("../components/TheFooter.vue")['default']
export const LazyCommonsSortJobOfferts: typeof import("../components/commons/SortJobOfferts.vue")['default']
export const LazyCommonsSwiperSlider: typeof import("../components/commons/SwiperSlider.vue")['default']
export const LazyFormContactForm: typeof import("../components/form/ContactForm.vue")['default']
export const LazyFormJobApplicationForm: typeof import("../components/form/JobApplicationForm.vue")['default']
export const LazyFormNewsletterTopicForm: typeof import("../components/form/NewsletterTopicForm.vue")['default']
export const LazyFormInputCheckbox: typeof import("../components/form/input/InputCheckbox.vue")['default']
export const LazyFormInputFile: typeof import("../components/form/input/InputFile.vue")['default']
export const LazyFormInputNumber: typeof import("../components/form/input/InputNumber.vue")['default']
export const LazyFormInputRadio: typeof import("../components/form/input/InputRadio.vue")['default']
export const LazyFormInputRange: typeof import("../components/form/input/InputRange.vue")['default']
export const LazyFormInputSelect: typeof import("../components/form/input/InputSelect.vue")['default']
export const LazyFormInputText: typeof import("../components/form/input/InputText.vue")['default']
export const LazyFormInputTextarea: typeof import("../components/form/input/InputTextarea.vue")['default']
export const LazyFormInputPromoFilterCheckbox: typeof import("../components/form/input/PromoFilterCheckbox.vue")['default']
export const LazyModalsBaseModal: typeof import("../components/modals/BaseModal.vue")['default']
export const LazyModalsJobFiltersModal: typeof import("../components/modals/JobFiltersModal.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
export const LazyNuxtPicture: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
export const LazyNuxtLinkLocale: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
export const LazySwitchLocalePathLink: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
export const LazyNuxtIcon: typeof import("../node_modules/nuxt-icons/dist/runtime/components/nuxt-icon.vue")['default']
export const LazyPAutoComplete: typeof import("primevue/autocomplete")['default']
export const LazyPCalendar: typeof import("primevue/calendar")['default']
export const LazyPCascadeSelect: typeof import("primevue/cascadeselect")['default']
export const LazyPCheckbox: typeof import("primevue/checkbox")['default']
export const LazyPChips: typeof import("primevue/chips")['default']
export const LazyPColorPicker: typeof import("primevue/colorpicker")['default']
export const LazyPDropdown: typeof import("primevue/dropdown")['default']
export const LazyPInputMask: typeof import("primevue/inputmask")['default']
export const LazyPInputNumber: typeof import("primevue/inputnumber")['default']
export const LazyPInputSwitch: typeof import("primevue/inputswitch")['default']
export const LazyPInputText: typeof import("primevue/inputtext")['default']
export const LazyPKnob: typeof import("primevue/knob")['default']
export const LazyPListbox: typeof import("primevue/listbox")['default']
export const LazyPMultiSelect: typeof import("primevue/multiselect")['default']
export const LazyPPassword: typeof import("primevue/password")['default']
export const LazyPRadioButton: typeof import("primevue/radiobutton")['default']
export const LazyPRating: typeof import("primevue/rating")['default']
export const LazyPSelectButton: typeof import("primevue/selectbutton")['default']
export const LazyPSlider: typeof import("primevue/slider")['default']
export const LazyPTextarea: typeof import("primevue/textarea")['default']
export const LazyPToggleButton: typeof import("primevue/togglebutton")['default']
export const LazyPTreeSelect: typeof import("primevue/treeselect")['default']
export const LazyPTriStateCheckbox: typeof import("primevue/tristatecheckbox")['default']
export const LazyPButton: typeof import("primevue/button")['default']
export const LazyPSpeedDial: typeof import("primevue/speeddial")['default']
export const LazyPSplitButton: typeof import("primevue/splitbutton")['default']
export const LazyPColumn: typeof import("primevue/column")['default']
export const LazyPRow: typeof import("primevue/row")['default']
export const LazyPColumnGroup: typeof import("primevue/columngroup")['default']
export const LazyPDataTable: typeof import("primevue/datatable")['default']
export const LazyPDataView: typeof import("primevue/dataview")['default']
export const LazyPDataViewLayoutOptions: typeof import("primevue/dataviewlayoutoptions")['default']
export const LazyPOrderList: typeof import("primevue/orderlist")['default']
export const LazyPOrganizationChart: typeof import("primevue/organizationchart")['default']
export const LazyPPaginator: typeof import("primevue/paginator")['default']
export const LazyPPickList: typeof import("primevue/picklist")['default']
export const LazyPTree: typeof import("primevue/tree")['default']
export const LazyPTreeTable: typeof import("primevue/treetable")['default']
export const LazyPTimeline: typeof import("primevue/timeline")['default']
export const LazyPVirtualScroller: typeof import("primevue/virtualscroller")['default']
export const LazyPAccordion: typeof import("primevue/accordion")['default']
export const LazyPAccordionTab: typeof import("primevue/accordiontab")['default']
export const LazyPCard: typeof import("primevue/card")['default']
export const LazyPDeferredContent: typeof import("primevue/deferredcontent")['default']
export const LazyPDivider: typeof import("primevue/divider")['default']
export const LazyPFieldset: typeof import("primevue/fieldset")['default']
export const LazyPPanel: typeof import("primevue/panel")['default']
export const LazyPScrollPanel: typeof import("primevue/scrollpanel")['default']
export const LazyPSplitter: typeof import("primevue/splitter")['default']
export const LazyPSplitterPanel: typeof import("primevue/splitterpanel")['default']
export const LazyPTabView: typeof import("primevue/tabview")['default']
export const LazyPTabPanel: typeof import("primevue/tabpanel")['default']
export const LazyPToolbar: typeof import("primevue/toolbar")['default']
export const LazyPConfirmDialog: typeof import("primevue/confirmdialog")['default']
export const LazyPConfirmPopup: typeof import("primevue/confirmpopup")['default']
export const LazyPDialog: typeof import("primevue/dialog")['default']
export const LazyPDynamicDialog: typeof import("primevue/dynamicdialog")['default']
export const LazyPOverlayPanel: typeof import("primevue/overlaypanel")['default']
export const LazyPSidebar: typeof import("primevue/sidebar")['default']
export const LazyPFileUpload: typeof import("primevue/fileupload")['default']
export const LazyPBreadcrumb: typeof import("primevue/breadcrumb")['default']
export const LazyPContextMenu: typeof import("primevue/contextmenu")['default']
export const LazyPDock: typeof import("primevue/dock")['default']
export const LazyPMenu: typeof import("primevue/menu")['default']
export const LazyPMenubar: typeof import("primevue/menubar")['default']
export const LazyPMegaMenu: typeof import("primevue/megamenu")['default']
export const LazyPPanelMenu: typeof import("primevue/panelmenu")['default']
export const LazyPSteps: typeof import("primevue/steps")['default']
export const LazyPTabMenu: typeof import("primevue/tabmenu")['default']
export const LazyPTieredMenu: typeof import("primevue/tieredmenu")['default']
export const LazyPMessage: typeof import("primevue/message")['default']
export const LazyPInlineMessage: typeof import("primevue/inlinemessage")['default']
export const LazyPToast: typeof import("primevue/toast")['default']
export const LazyPCarousel: typeof import("primevue/carousel")['default']
export const LazyPGalleria: typeof import("primevue/galleria")['default']
export const LazyPImage: typeof import("primevue/image")['default']
export const LazyPAvatar: typeof import("primevue/avatar")['default']
export const LazyPAvatarGroup: typeof import("primevue/avatargroup")['default']
export const LazyPBadge: typeof import("primevue/badge")['default']
export const LazyPBlockUI: typeof import("primevue/blockui")['default']
export const LazyPChip: typeof import("primevue/chip")['default']
export const LazyPInplace: typeof import("primevue/inplace")['default']
export const LazyPScrollTop: typeof import("primevue/scrolltop")['default']
export const LazyPSkeleton: typeof import("primevue/skeleton")['default']
export const LazyPProgressBar: typeof import("primevue/progressbar")['default']
export const LazyPProgressSpinner: typeof import("primevue/progressspinner")['default']
export const LazyPTag: typeof import("primevue/tag")['default']
export const LazyPTerminal: typeof import("primevue/terminal")['default']
export const LazyErrorMessage: typeof import("vee-validate")['ErrorMessage']
export const LazyField: typeof import("vee-validate")['Field']
export const LazyFieldArray: typeof import("vee-validate")['FieldArray']
export const LazyForm: typeof import("vee-validate")['Form']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
