// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 24/1/2025, 12:13:23
const configMerger = require("/Users/gdalmaso/projects/airisc/airisc-fe/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.ts")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["/Users/gdalmaso/projects/airisc/airisc-fe/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/gdalmaso/projects/airisc/airisc-fe/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/gdalmaso/projects/airisc/airisc-fe/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/gdalmaso/projects/airisc/airisc-fe/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/gdalmaso/projects/airisc/airisc-fe/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/gdalmaso/projects/airisc/airisc-fe/plugins/**/*.{js,ts,mjs}","/Users/gdalmaso/projects/airisc/airisc-fe/composables/**/*.{js,ts,mjs}","/Users/gdalmaso/projects/airisc/airisc-fe/utils/**/*.{js,ts,mjs}","/Users/gdalmaso/projects/airisc/airisc-fe/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/gdalmaso/projects/airisc/airisc-fe/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/gdalmaso/projects/airisc/airisc-fe/app.config.{js,ts,mjs}"] } }));

module.exports = config
